CREATE DATABASE BD_DISTRIBUIDORA;
USE BD_DISTRIBUIDORA; 

CREATE TABLE PRODUCTOS
(
ID_PRODUCTO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
PRECIO_UNIDAD BIGINT NOT NULL,
STOCK_DISPONIBLE INT NOT NULL,
DESCRIPCION VARCHAR (300) NOT NULL,
FECHA_VENCIMIENTO DATE NOT NULL,
FOTO BLOB,
FK_ID_MARCA INT NOT NULL,
FK_ID_CATEGORIA_PRODUCTO INT NOT NULL
);

CREATE TABLE PROVEEDORES 
(
ID_PROVEEDOR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE_PROVEEDOR VARCHAR (20) NOT NULL,
NIT_PROVEEDOR INT NOT NULL,
DIRECCION VARCHAR (30) NOT NULL,
TELEFONO INT NOT NULL,
CORREO VARCHAR (30) NOT NULL
);

CREATE TABLE VENTAS
(
ID_VENTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FECHA DATE NOT NULL,
TOTAL BIGINT NOT NULL,
PAGO_REALIZADO VARCHAR (60) NULL,
FK_ID_USUARIO INT NOT NULL,
FK_ID_PRODUCTO INT NOT NULL
);

CREATE TABLE DETALLES_VENTAS
(
ID_DETALLE_VENTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FK_ID_VENTA INT NOT NULL,
FECHA DATE NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO_PRODUCTO BIGINT NOT NULL,
SUBTOTAL BIGINT NOT NULL,
IVA INT NOT NULL,
TOTAL BIGINT NOT NULL
);

CREATE TABLE PERMISOS 
(
ID_PERMISO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(80) NOT NULL 
);

CREATE TABLE ROLES_PERMISOS
(
FK_ID_PERMISO INT NOT NULL,
FK_ID_ROL INT NOT NULL
);

CREATE TABLE ROLES
(
ID_ROL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOM_ROL VARCHAR (40) NOT NULL
);

CREATE TABLE USUARIOS 
(
ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NUMERO_DOCUMENTO INT NOT NULL,
PRIMER_NOMBRE VARCHAR (50) NOT NULL,
SEGUNDO_NOMBRE VARCHAR (50) NULL,
PRIMER_APELLIDO VARCHAR (50) NOT NULL,
SEGUNDO_APELLIDO VARCHAR (50) NULL,
DIRECCION VARCHAR(70) NOT  NULL,
TELEFONO INT NOT NULL, 
CORREO VARCHAR (30) NOT NULL,
CONTRASEÑA VARCHAR (20) NOT NULL,
FK_ID_ROL INT NOT NULL,
FK_TIPO_DOCUMENTO INT NOT NULL,
FK_ID_ESTADO INT NOT NULL
);

CREATE TABLE ESTADOS
 (
 ID_ESTADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
 NOMBRE VARCHAR (40) NOT NULL
 );
 
 CREATE TABLE MARCAS 
 (
 ID_MARCA INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
 NOMBRE_MARCA VARCHAR (20) NOT NULL 
 );
 
 CREATE TABLE CATEGORIAS_PRODUCTOS
 (
 ID_CATEGORIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
 NOMBRE_CATEGORIA VARCHAR (40) NOT NULL
 );
 
 CREATE TABLE TIPOS_DOCUMENTOS 
 (
 ID_TIPO_DOCUMENTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NOMBRE_DOCUMENTO VARCHAR (30) NOT NULL,
 SIGLAS VARCHAR (20) NOT NULL
 );
 
 CREATE TABLE PROVEEDOR_PRODUCTO
 (
 FK_ID_PROVEEDOR INT NOT NULL,
 FK_ID_PRODUCTO INT NOT NULL
 );
 
 CREATE TABLE FACTURAS_COMPRAS
 (
 ID_FACTURA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 FECHA DATE NOT NULL,
 PRECIO_UNIDAD BIGINT NOT NULL,
 CANTIDAD INT NOT NULL,
 SUBTOTAL BIGINT NOT NULL,
 IVA INT NOT NULL,
 TOTAL BIGINT NOT NULL,
 FK_ID_COMPRA INT NOT NULL
 );
 
 CREATE TABLE COMPRAS
 (
 ID_COMPRA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 FECHA DATE NOT NULL,
 TOTAL BIGINT NOT NULL,
 PAGO_REALIZADO VARCHAR (60) NULL,
 FK_ID_PROVEEDOR INT NOT NULL
 );
 
 CREATE TABLE DETALLES_COMPRAS
 (
 FK_ID_COMPRA INT NOT NULL ,
 FK_ID_PRODUCTO INT NOT NULL,
 FECHA DATE NOT NULL,
 PRECIO_PRODUCTO BIGINT NOT NULL,
 CANTIDAD INT NOT NULL,
 SUBTOTAL BIGINT NOT NULL,
 IVA INT NOT NULL,
 TOTAL BIGINT NOT NULL
 );
 
 CREATE TABLE INVENTARIOS
 (
 ID_INVENTARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NOMBRE VARCHAR(50) NOT NULL
 );
 
 CREATE TABLE INVENTARIO_ENTRADAS
 (
 FK_ID_PRODUCTO INT NOT NULL,
 FK_ID_INVENTARIO INT NOT NULL,
 CANTIDAD INT NOT NULL,
 TOTAL BIGINT NOT NULL
 );
 
 CREATE TABLE INVENTARIO_SALIDAS
 (
 FK_ID_DETALLE_VENTA INT NOT NULL,
 FK_ID_INVENTARIO INT NOT NULL,
 CANTIDAD INT NOT NULL,
 TOTAL BIGINT NOT NULL
 );
 
 CREATE TABLE TIPO_PETICIONES 
 (
 ID_TIPO_PETICION INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NOMBRE VARCHAR(80) NOT NULL
 );
 
 CREATE TABLE PETICIONES
 (
 ID_PETICION INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 FK_ID_TIPO_PETICION INT NOT NULL,
 DESCRIPCION VARCHAR(500) NOT NULL,
 FK_ID_USUARIO INT NOT NULL
 );
 
 CREATE TABLE RESPUESTAS
 (
 ID_RESPUESTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 DESCRIPCION VARCHAR(500) NOT NULL,
 FK_ID_PETICION INT NOT NULL,
 FK_ID_USUARIO INT NOT NULL
 );
 

 
 
ALTER TABLE PRODUCTOS ADD CONSTRAINT  FOREIGN KEY (FK_ID_MARCA) REFERENCES MARCAS (ID_MARCA) ON UPDATE CASCADE;
ALTER TABLE PRODUCTOS ADD CONSTRAINT  FOREIGN KEY (FK_ID_CATEGORIA_PRODUCTO) REFERENCES CATEGORIAS_PRODUCTOS (ID_CATEGORIA) ON UPDATE CASCADE;
ALTER TABLE VENTAS ADD CONSTRAINT  FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO) ON UPDATE CASCADE;
ALTER TABLE VENTAS ADD CONSTRAINT  FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO) ON UPDATE CASCADE;
ALTER TABLE DETALLES_VENTAS ADD CONSTRAINT  FOREIGN KEY (FK_ID_VENTA) REFERENCES VENTAS (ID_VENTA) ON UPDATE CASCADE;
ALTER TABLE ROLES_PERMISOS ADD CONSTRAINT  FOREIGN KEY (FK_ID_PERMISO) REFERENCES PERMISOS (ID_PERMISO) ON UPDATE CASCADE;
ALTER TABLE ROLES_PERMISOS ADD CONSTRAINT  FOREIGN KEY (FK_ID_ROL) REFERENCES ROLES (ID_ROL) ON UPDATE CASCADE;
ALTER TABLE USUARIOS ADD CONSTRAINT  FOREIGN KEY (FK_ID_ROL) REFERENCES ROLES (ID_ROL) ON UPDATE CASCADE;
ALTER TABLE USUARIOS ADD CONSTRAINT  FOREIGN KEY (FK_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTOS (ID_TIPO_DOCUMENTO) ON UPDATE CASCADE;
ALTER TABLE USUARIOS ADD CONSTRAINT  FOREIGN KEY (FK_ID_ESTADO) REFERENCES ESTADOS (ID_ESTADO) ON UPDATE CASCADE;
ALTER TABLE PROVEEDOR_PRODUCTO ADD CONSTRAINT FOREIGN KEY (FK_ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDOR) ON UPDATE CASCADE;
ALTER TABLE PROVEEDOR_PRODUCTO ADD CONSTRAINT FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO) ON UPDATE CASCADE;
ALTER TABLE COMPRAS ADD CONSTRAINT  FOREIGN KEY (FK_ID_PROVEEDOR) REFERENCES PROVEEDORES (ID_PROVEEDOR) ON UPDATE CASCADE;
ALTER TABLE DETALLES_COMPRAS ADD CONSTRAINT  FOREIGN KEY (FK_ID_COMPRA) REFERENCES COMPRAS (ID_COMPRA) ON UPDATE CASCADE;
ALTER TABLE DETALLES_COMPRAS ADD CONSTRAINT  FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO) ON UPDATE CASCADE;
ALTER TABLE INVENTARIO_ENTRADAS ADD CONSTRAINT FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO) ON UPDATE CASCADE;
ALTER TABLE INVENTARIO_ENTRADAS ADD CONSTRAINT FOREIGN KEY (FK_ID_INVENTARIO) REFERENCES INVENTARIOS (ID_INVENTARIO) ON UPDATE CASCADE;
ALTER TABLE INVENTARIO_SALIDAS ADD CONSTRAINT FOREIGN KEY (FK_ID_DETALLE_VENTA) REFERENCES DETALLES_VENTAS (ID_DETALLE_VENTA) ON UPDATE CASCADE;
ALTER TABLE INVENTARIO_SALIDAS ADD CONSTRAINT FOREIGN KEY (FK_ID_INVENTARIO) REFERENCES INVENTARIOS (ID_INVENTARIO) ON UPDATE CASCADE;
ALTER TABLE PETICIONES ADD CONSTRAINT FOREIGN KEY (FK_ID_TIPO_PETICION) REFERENCES TIPO_PETICIONES (ID_TIPO_PETICION) ON UPDATE CASCADE;
ALTER TABLE PETICIONES ADD CONSTRAINT FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO) ON UPDATE CASCADE;
ALTER TABLE RESPUESTAS ADD CONSTRAINT FOREIGN KEY (FK_ID_PETICION) REFERENCES PETICIONES (ID_PETICION) ON UPDATE CASCADE;
ALTER TABLE RESPUESTAS ADD CONSTRAINT FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO) ON UPDATE CASCADE;





